export const FETCH_TIME = 'FETCH_TIME';

export const FETCH_HOUR = 'FETCH_HOUR';
export const FETCH_MINUTE = 'FETCH_MINUTE';
export const FETCH_SECOND = 'FETCH_SECOND';

export const FETCH_HOUR_ERROR = 'FETCH_HOUR_ERROR';
export const FETCH_MINUTE_ERROR = 'FETCH_MINUTE_ERROR';
export const FETCH_SECOND_ERROR = 'FETCH_SECOND_ERROR';
